backend:
    name: github
    repo: gustavofoa/dicasdepython.com.br
    branch: master
    site_domain: dicasdepythoncombr.netlify.com

media_folder: "content/images"
public_folder: "/images"
publish_mode: editorial_workflow

collections:
  - name: "post"
    label: "Artigos"
    folder: "content/posts"
    sort: "date:desc"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Data de publicacao", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "Autor", name: "author", widget: "string", default: "Gustavo Furtado de Oliveira Alves"}
      - {label: "Categoria", name: "category", widget: "select", options: ["Ferramentas", "Frameworks", "Fundamentos", "Util"], default: "Util"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Imagem de destaque", name: "image", widget: "image"}
      - {label: "Conteudo", name: "body", widget: "markdown"}
